[project]
name = "FinancialModel"
uuid = "a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6"
authors = ["John Schwitz"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-cc8e4c68c72c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d795533"